import runtimeSource from './overlayRuntime.js?raw'

/**
 * Files of the exported NUI page (html/). The page is a transparent full-screen
 * layer with one canvas that client.lua keeps positioned over the radar; the
 * effects are painted by the same runtime the editor preview uses.
 */

export const nuiIndexHtml = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <canvas id="radar-fx"></canvas>
    <script src="overlay.js"></script>
    <script src="script.js"></script>
  </body>
</html>
`

export const nuiStyleCss = `html,
body {
  margin: 0;
  width: 100%;
  height: 100%;
  overflow: hidden;
  background: transparent;
  pointer-events: none;
}

#radar-fx {
  position: absolute;
  display: none;
  pointer-events: none;
}
`

/** The shared effects runtime as a classic script (globals instead of exports). */
export const nuiOverlayJs = `// Generated by LABSEVE7 Map Studio: radar overlay effects (same code as the editor preview).
${runtimeSource.replace(/^export /gm, '')}`

export const nuiScriptJs = `// Generated by LABSEVE7 Map Studio.
// client.lua sends:
//   { action: "fx:config", fx: { ids, intensity, speed, color } }
//   { action: "fx:layout", visible, rect: { x, y, w, h } }   (radar rectangle, 0-1 of the screen)
(function () {
  var canvas = document.getElementById("radar-fx");
  var ctx = canvas.getContext("2d");
  var state = { fx: null, rect: null, visible: false, box: null };
  var raf = 0;
  var last = 0;
  var start = performance.now();

  function layout() {
    var W = window.innerWidth;
    var H = window.innerHeight;
    var r = state.rect;
    var w = r.w * W;
    var h = r.h * H;
    var pad = Math.ceil(h * FX_BLEED);
    var dpr = window.devicePixelRatio || 1;
    canvas.style.left = r.x * W - pad + "px";
    canvas.style.top = r.y * H - pad + "px";
    canvas.style.width = w + pad * 2 + "px";
    canvas.style.height = h + pad * 2 + "px";
    canvas.width = Math.max(1, Math.round((w + pad * 2) * dpr));
    canvas.height = Math.max(1, Math.round((h + pad * 2) * dpr));
    state.box = { x: pad, y: pad, w: w, h: h, dpr: dpr };
  }

  function frame(now) {
    raf = 0;
    if (!shown()) return;
    raf = requestAnimationFrame(frame);
    // 30 fps is plenty for HUD effects and keeps the NUI cheap.
    if (now - last < 32) return;
    last = now;
    var b = state.box;
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.setTransform(b.dpr, 0, 0, b.dpr, 0, 0);
    paintRadarFx(ctx, state.fx, (now - start) / 1000, { x: b.x, y: b.y, w: b.w, h: b.h });
  }

  function shown() {
    return !!(state.visible && state.rect && state.fx && state.fx.ids && state.fx.ids.length);
  }

  function update() {
    if (!shown()) {
      canvas.style.display = "none";
      return;
    }
    layout();
    canvas.style.display = "block";
    if (!raf) raf = requestAnimationFrame(frame);
  }

  window.addEventListener("message", function (event) {
    var data = event.data || {};
    if (data.action === "fx:config") state.fx = data.fx;
    else if (data.action === "fx:layout") {
      state.visible = !!data.visible;
      state.rect = data.rect || null;
    } else return;
    update();
  });
  window.addEventListener("resize", function () {
    if (shown()) update();
  });

  // Tell client.lua the page is ready (retries until the callback answers).
  var resource = typeof GetParentResourceName === "function" ? GetParentResourceName() : "minimap";
  (function ping() {
    fetch("https://" + resource + "/fxReady", {
      method: "POST",
      headers: { "Content-Type": "application/json; charset=UTF-8" },
      body: "{}",
    })
      .then(function (res) {
        if (!res.ok) throw new Error(String(res.status));
      })
      .catch(function () {
        setTimeout(ping, 1500);
      });
  })();
})();
`
